# Generated by Django 5.2.6 on 2025-09-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='door_num',
            field=models.IntegerField(),
        ),
    ]
