# Generated by Django 5.2.6 on 2025-09-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_alter_car_door_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('lp_gas', 'LP Gas')], default='gas'),
        ),
    ]
