# Generated by Django 5.2.6 on 2025-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='roof_type',
            field=models.CharField(choices=[('solid', 'Solid'), ('sunroof', 'Sunroof'), ('convertible', 'Convertible')], default='solid', max_length=25),
        ),
    ]
