# Generated by Django 5.2.6 on 2025-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_car_roof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='roof_type',
            field=models.CharField(choices=[('solid', 'Solid'), ('sunroof', 'Sunroof'), ('convertible', 'Convertible')], default='solid'),
        ),
    ]
